### ISSUE TITLE
Un-ordered output due to missing `mirror_step` variable

### ISSUE THREAD

**Issue by ank1m** [nasa/stitchee#198]
### Issue:
StitchEE uses `mirror_step` variable to sort granules but `l2ss` removes `mirror_step` from the output when `variable subsetting` is requested.

### Solutions:
- Request `l2ss` to always include `mirror_step` and `xtrack`, similarly to `longitude` and `latitude` logic:
   - **Cons:** also makes this approach very TEMPO specific
- Request EDS client to revise their `variable subsetting` interface by removing non-optional variables from selection and pass Harmony requests always including these variables:
   - **Cons:** direct access to Harmony API or via `harmony-py` would still allow user to remove non-optional variables
- Discuss other solutions: creating additional flag for non-optional variables to be passed by Harmony to the services?

### Workaround
- Use `longitude`, `filename` or `time` to sort granules

**Comment by chris-durbin** [comment]
There's a concept of 'coordinate' variables that the L2SS team asked for a couple years ago (HARMONY-1121). I'd check with them if they keep all of the coordinate variables in the output file when they perform variable subsetting. If so that could be another solution - define mirror_step and xtrack as coordinate variables in UMM-Var.
